services:
  order_app:
    build: .
    container_name: order-service-app
    volumes:
      - ../order-service:/var/www
    networks:
      - laravel-net
    depends_on:
      order_db:
        condition: service_healthy
  message_broker:
    image: rabbitmq:3.9-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"   # Port untuk aplikasi
      - "15672:15672" # Port untuk web management UI
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    networks: # <--- TAMBAHKAN BLOK INI
    - laravel-net

  order_web:
    image: nginx:stable-alpine
    container_name: order_service_nginx
    ports:
      - "8003:80"
    volumes:
      - ../order-service:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - laravel-net
    depends_on:
      - order_app

  order_db:
    image: mysql:8
    container_name: order_service_db
    environment:
      MYSQL_DATABASE: order_service_db
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - order_db_data:/var/lib/mysql
    ports:
      - "3310:3306"
    networks:
      - laravel-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  laravel-net:
    external: true

volumes:
  order_db_data: