services:
  product_app:
    build: .
    container_name: product-service-app
    volumes:
      - ../product-service:/var/www
    networks:
      - laravel-net
    depends_on:
      product_db:
        condition: service_healthy

  product_web:
    image: nginx:stable-alpine
    container_name: product_service_nginx
    ports:
      - "8002:80"
    volumes:
      - ../product-service:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - laravel-net
    depends_on:
      - product_app

  product_db:
    image: mysql:8
    container_name: product_service_db
    environment:
      MYSQL_DATABASE: product_service_db
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - product_db_data:/var/lib/mysql
    ports:
      - "3311:3306"
    networks:
      - laravel-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  laravel-net:
    external: true

volumes:
  product_db_data: {}