services:
  user_app:
    build: .
    container_name: user-service-app
    volumes:
      - ../user-service:/var/www
    networks:
      - laravel-net
    depends_on:
      user_db:
        condition: service_healthy

  user_web:
    image: nginx:stable-alpine
    container_name: user_service_nginx
    ports:
      - "8001:80"
    volumes:
      - ../user-service:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - laravel-net
    depends_on:
      - user_app

  user_db:
    image: mysql:8
    container_name: user_service_db
    environment:
      MYSQL_DATABASE: user_service_db
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - user_db_data:/var/lib/mysql
    ports:
      - "3309:3306"
    networks:
      - laravel-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  laravel-net:
    external: true

volumes:
  user_db_data: